package com.manoj;

import java.io.FileWriter;
import java.io.IOException;

public class HelloManoj {

    public static void main(String[] args) throws IOException {

        String html = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Hello Manoj</title>
        </head>
        <body>
            <h1>Hello Manoj 👋</h1>
            <p>Generated by Java & deployed using GitHub Actions</p>
        </body>
        </html>
        """;

        try (FileWriter writer = new FileWriter("target/index.html")) {
            writer.write(html);
        }

        System.out.println("✅ index.html generated successfully");
    }
}
